name: shoppe
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.4
dependencies:
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  dio: ^5.9.2
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^10.0.0
  flutter_svg: ^2.2.4
  freezed_annotation: ^3.1.0
  get_it: ^9.2.1
  json_annotation: ^4.11.0
  pinput: ^6.0.2
  pretty_dio_logger: ^1.4.0
  retrofit: ^4.9.2
  shared_preferences: ^2.5.5
  shimmer: ^3.0.0

dev_dependencies:
  build_runner: ^2.13.1
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.13.1
  retrofit_generator: ^10.2.5

flutter_native_splash:
  color: "#9775FA"
  image: assets/master/splash_screen.png
  android_12:
    image: assets/master/splash_screen.png
    color: "#9775FA"

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/icons/
    - assets/master/
  fonts:
    - family: "Cairo"
      fonts:
        - asset: assets/fonts/cairo/black.ttf
          weight: 200
        - asset: assets/fonts/cairo/light.ttf
          weight: 300
        - asset: assets/fonts/cairo/regular.ttf
          weight: 400
        - asset: assets/fonts/cairo/medium.ttf
          weight: 500
        - asset: assets/fonts/cairo/semi_bold.ttf
          weight: 600
        - asset: assets/fonts/cairo/bold.ttf
          weight: 700
        - asset: assets/fonts/cairo/extra_bold.ttf
          weight: 800
        - asset: assets/fonts/cairo/black.ttf
          weight: 900

flutter_icons:
  android: true
  ios: true
  image_path: "assets/master/icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/master/icon.png"
